name: Build Docker Image on Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Git tag as an environment variable
        run: echo "GIT_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: set lower case owner name
        run: |
          echo "GH_REPO_LC=${GH_REPO,,}" >>${GITHUB_ENV}
        env:
          GH_REPO: '${{ github.repository }}'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.GH_REPO_LC }}:${{ github.sha }}
            ghcr.io/${{ env.GH_REPO_LC }}:latest
            ghcr.io/${{ env.GH_REPO_LC }}:${{ env.GIT_TAG }}
          build-args: |
            GIT_TAG=${GIT_TAG}
